### ISSUE TITLE
*** Error in `9vx': free(): invalid pointer: 0xbf95d89f ***

### ISSUE THREAD

**Issue by jibanes** [0intro/vx32#1]
In vx32/src/(gdb) where
#0  0xb771fcf9 in __kernel_vsyscall ()
#1  0xb7416dc0 in __libc_signal_restore_set (set=0xa6626810) at ../sysdeps/unix/sysv/linux/nptl-signals.h:79
#2  __GI_raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xb7418287 in __GI_abort () at abort.c:89
#4  0xb745237f in __libc_message (do_abort=<optimized out>, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:175
#5  0xb7458fb7 in malloc_printerr (action=<optimized out>, str=0xb7548d80 "free(): invalid pointer", ptr=<optimized out>, ar_ptr=0x0) at malloc.c:5049
#6  0xb74597f6 in _int_free (av=0x0, p=0xbf95d897, have_lock=have_lock@entry=0) at malloc.c:3905
#7  0xb745d0dd in __GI___libc_free (mem=0xbf95d89f) at malloc.c:2985
#8  0x800a6ccb in _xattach (label=0x800c03f7 "9vx", winsize=0x0) at 9vx/x11/x11-init.c:92
#9  0x800a867e in attachscreen (r=0xa6626f00, chan=0xa6626eec, depth=0xa6626ef0, width=0xa6626ef4, softscreen=0xa6626ef8, X=0xa6626efc) at 9vx/x11/x11-kernel.c:161
#10 0x8002c272 in kickscreen () at 9vx/term.c:353
#11 0x8002871c in init0 () at 9vx/main.c:452
#12 0x00000000 in ?? ()

fix:

9vx/x11/x11-init.c line 92: free(disp)
You shouldn't use free here, disp isn't malloc'd, just remove the free(disp).

**Comment by 0intro** [comment]
Fixed. Thanks.
